name: Screenshot-Based Job Hunter

on:
  schedule:
    # Multiple schedules for better reliability
    - cron: '0,30 * * * *'    # Primary: Every 30 minutes
    - cron: '5,35 * * * *'    # Backup: 5min offset
    - cron: '10,40 * * * *'   # Backup: 10min offset
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  screenshot-job-hunt:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          gnupg \
          unzip \
          curl \
          xvfb \
          libnss3 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libxss1 \
          libasound2
        
    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Verify Chrome installation
      run: |
        google-chrome --version
        which google-chrome
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Restore previous state from cache
      uses: actions/cache/restore@v4
      with:
        path: |
          screenshot_jobs_state.json
          nvidia_screenshot.txt
          intel_screenshot.txt
        key: screenshot-job-hunter-state-${{ github.repository }}
        restore-keys: |
          screenshot-job-hunter-state-${{ github.repository }}
          screenshot-job-hunter-state-
        
    - name: Run Screenshot Job Hunter
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        CHANGE_THRESHOLD: ${{ vars.CHANGE_THRESHOLD || '0.5' }}
        SAVE_DEBUG_IMAGES: ${{ vars.SAVE_DEBUG_IMAGES || 'false' }}
      run: |
        cd screenshot-version
        python jobHunt_screenshot.py
      
    - name: Save state to cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          screenshot-version/screenshot_jobs_state.json
          screenshot-version/nvidia_screenshot.txt
          screenshot-version/intel_screenshot.txt
        key: screenshot-job-hunter-state-${{ github.repository }}-${{ github.run_number }}
        
    - name: Upload debug images (if any)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-images-${{ github.run_number }}
        path: |
          screenshot-version/debug_*.png
        retention-days: 7
        if-no-files-found: ignore
        
    - name: Upload logs as artifacts (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-hunter-logs-${{ github.run_number }}
        path: |
          screenshot-version/*.log
          screenshot-version/screenshot_jobs_state.json
          screenshot-version/*_screenshot.txt
        retention-days: 7